# Generated by Django 3.2.5 on 2021-08-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0015_seat_reserve'),
        ('reservationapp', '0002_alter_reservation_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='concertapp.schedule'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='concertapp.seat'),
        ),
    ]
