# Generated by Django 3.2.5 on 2021-08-11 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservationapp', '0009_auto_20210811_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
