# Generated by Django 3.2.5 on 2021-08-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0011_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
