# Generated by Django 3.2.5 on 2021-08-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0013_alter_reservation_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='not same reservation',
        ),
    ]
