# Generated by Django 3.2.5 on 2021-08-14 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0020_auto_20210814_0304'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservationapp', '0014_remove_reservation_not same reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservationapp.reservation')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='concertapp.schedule')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='concertapp.seat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
