# Generated by Django 3.2.5 on 2021-07-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='공연 이름')),
                ('category', models.CharField(choices=[('concert', '콘서트'), ('musical', '뮤지컬'), ('classic', '클래식')], max_length=10)),
                ('start_dt', models.DateTimeField(verbose_name='공연 시작 시간')),
                ('end_dt', models.DateTimeField(verbose_name='공연 종료 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=10, verbose_name='좌석 등급')),
                ('seat_number', models.IntegerField()),
                ('reservation', models.BooleanField(default=False)),
                ('concert_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='concertapp.concerthall')),
            ],
        ),
        migrations.AddField(
            model_name='concerthall',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concertapp.performance'),
        ),
    ]
