# Generated by Django 3.2.5 on 2021-07-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.RemoveField(
            model_name='concerthall',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='start_dt',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='공연 시작 시간')),
                ('end_dt', models.DateTimeField(verbose_name='공연 종료 시간')),
                ('concert_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='concertapp.concerthall')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='concertapp.performance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('concert_hall', 'start_dt', 'end_dt'), name='place revervation time'),
        ),
    ]
