# Generated by Django 3.2.5 on 2021-07-17 19:29

import concertapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0002_auto_20210717_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='poster',
            field=models.ImageField(null=True, upload_to=concertapp.models.poster_dirs_path),
        ),
    ]
