# Generated by Django 3.2.5 on 2021-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0003_performance_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='ticket_open_dt',
            field=models.DateTimeField(null=True, verbose_name='티켓 예매 시작 일시'),
        ),
    ]
