# Generated by Django 3.2.5 on 2021-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0005_performance_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='end_dt',
            field=models.DateField(null=True, verbose_name='전체 공연 일정 종료 일자'),
        ),
        migrations.AddField(
            model_name='performance',
            name='start_dt',
            field=models.DateField(null=True, verbose_name='전체 공연 일정 시작 일자'),
        ),
    ]
