# Generated by Django 3.2.5 on 2021-07-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0006_auto_20210723_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='end_dt',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='start_dt',
            new_name='start_day',
        ),
    ]
