# Generated by Django 3.2.5 on 2021-07-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0007_auto_20210723_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='seat',
            name='area',
            field=models.CharField(max_length=10, null=True, verbose_name='공연장 구역'),
        ),
    ]
