# Generated by Django 3.2.5 on 2021-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0008_auto_20210727_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
