# Generated by Django 3.2.5 on 2021-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0011_alter_seat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='오 와 열 중 열을 뜻함'),
        ),
    ]
