# Generated by Django 3.2.5 on 2021-08-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0013_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='description',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='concertapp.performance'),
        ),
    ]
