# Generated by Django 3.2.5 on 2021-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0014_auto_20210811_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
