# Generated by Django 3.2.5 on 2021-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0016_remove_seat_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
