# Generated by Django 3.2.5 on 2021-08-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0018_remove_seat_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['floor', 'area', 'row', 'number']},
        ),
    ]
