# Generated by Django 3.2.5 on 2021-08-14 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0019_alter_seat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_seat', to='concertapp.schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_seat', to='concertapp.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='performanceseat',
            constraint=models.UniqueConstraint(fields=('schedule', 'seat'), name='not same reservation'),
        ),
    ]
