# Generated by Django 3.2.5 on 2021-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0020_auto_20210814_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='ticket_close_dt',
            field=models.DateTimeField(null=True, verbose_name='티켓 예매 종료 일시'),
        ),
    ]
