# Generated by Django 3.2.5 on 2021-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0021_performance_ticket_close_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceseat',
            name='price',
            field=models.ImageField(default=100, upload_to=''),
        ),
    ]
